site_name: "Knox Music"
site_url: "https://italo.page"

docs_dir: source
site_dir: mkdocs_build

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top

nav:
  - Home: index.md
  - About me: about.md
  - Pricing: pricing.md
  - Contact: contact.md
  - Mixes: mixes.md
  - Music: music.md
  - Information guide: guide.md

  #pygments_style: "github-dark"

markdown_extensions:
  - admonition
  - pymdownx.blocks.details

plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true