site_name: "Knox Music"
site_url: "https://italo.page/music"

docs_dir: source
site_dir: mkdocs_build

theme:
  name: shadcn
  pygments_style: "github-dark"

markdown_extensions:
  - admonition
  - pymdownx.blocks.details